name: docker 

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker.yml'

env:
  VERSION_SLMIX: v1.0.0-beta
  RELEASE_DATE: 2025061305 # Increase to release (not used anywhere)

jobs:
  docker:
    env:
        IMAGE_NAME: studio-link/mix/slmix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log into registry
      uses: docker/login-action@v3
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        docker build -t slmix .

    - name: Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag slmix ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_SLMIX }}
        docker tag slmix ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_SLMIX }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest

